### PR TITLE
Feature/install tailwindcss

### PR DESCRIPTION
**Pull request by Sanan4li**

### CODE REVIEW

**Comment by schraderweb** [comment]
Hi Sanan,

Please create a new page on the site tjwaterfrontservices.com called:

6-tips-for-maintaining-your-seawalls.html

Please use the attached article for the content.

If it helps, here is an existing page with an article:
https://tjwaterfrontservices.com/tips-for-maintaining-boat-lift.html

Thanks!

FTP:

ny.storage.bunnycdn.com user: tjwaterfront

pw: 59c32cc4-7fe6-427d-9b5fc1ac9e85-4ea3-4971

Bret Schrader
Account Manager at [Schrader.co](https://schrader.co)
1568 State St. #7
Grawn, MI 49637
Phone: (231) 620-3620

------- Original Message -------

**Comment by Sanan4li** [comment]
Sorry I didn'r read this email yesterday. Let's have a meeting tonight. It
will be your day time.

**Comment by schraderweb** [comment]
OK....lets meet about 11am my time....iin about 3 1/2 hours from when this email was sent.

meet.google.com/pdu-fkub-ihm

Bret Schrader
Account Manager at [Schrader.co](https://schrader.co)
1568 State St. #7
Grawn, MI 49637
Phone: (231) 620-3620

------- Original Message -------

**Comment by schraderweb** [comment]
Can you please add this new page today?

You can refer to the other web page I linked so you can mimic that look.

Thanks!

Bret Schrader
Account Manager at [Schrader.co](https://schrader.co)
1568 State St. #7
Grawn, MI 49637
Phone: (231) 620-3620

------- Original Message -------

**Comment by Sanan4li** [comment]
Hi, I am extremely sorry for not attending the meeting. I have almost
completed the home page and pushed the code on the github. Just some of the
things need to be fixed and have to add the content. I will start working
on the rest of the pages and hopefully, it will be completed this weekend.

**Comment by schraderweb** [comment]
Hi Sanan,

Can we meet about 12 my time....in about 1 hour from when this email was sent.

meet.google.com/pdu-fkub-ihm

Bret Schrader
Account Manager at [Schrader.co](https://schrader.co)
1568 State St. #7
Grawn, MI 49637
Phone: (231) 620-3620

------- Original Message -------

**Comment by Sanan4li** [comment]
No, sorry I will be late. I will tell you about time

**Comment by schraderweb** [comment]
OK....pls let me know when to meet today..thanks!

Bret Schrader
Account Manager at [Schrader.co](https://schrader.co)
1568 State St. #7
Grawn, MI 49637
Phone: (231) 620-3620

------- Original Message -------

**Comment by Sanan4li** [comment]
Can we meet in 30 mins? It will be 4PM your time.
Please let me know.

**Comment by schraderweb** [comment]
Its hard for me to meet after 2pm my time....can we schedule a time for
tomorrow?

Between 10am and 2pm my time?

Were you able to add that new page to the TJ Waterfront site?

Bret Schrader
Account Manager at [Schrader.co](https://schrader.co)
1568 State St. #7
Grawn, MI 49637
Phone: (231) 620-3620

------- Original Message -------

**Comment by Sanan4li** [comment]
No, that's what I had to ask you about. Let's meet at 10.30pm my time.
It will be 1.30pm your time.

**Comment by schraderweb** [comment]
OK..lets meet then:

meet.google.com/pdu-fkub-ihm

Bret Schrader
Account Manager at [Schrader.co](https://schrader.co)
1568 State St. #7
Grawn, MI 49637
Phone: (231) 620-3620

------- Original Message -------

**Comment by schraderweb** [comment]
OK...lets meet here in a few mins:

meet.google.com/pdu-fkub-ihm

Bret Schrader
Account Manager at [Schrader.co](https://schrader.co)
1568 State St. #7
Grawn, MI 49637
Phone: (231) 620-3620

------- Original Message -------

**Comment by Sanan4li** [comment]
Hi bret, I am still not able to create the tips page in the same website.
That website has many many issues. I had to download 700+ files and the
filezillaw was disconnecting again and again.
[image: image.png]
The website is having issues because of different CSS and Javascript
libraries. I have tried hard but can't figure out why I see a blank page on
local project. The developer has literally created this site into wordpress
and then converted into a simple HTML CSS site. It has almost 100+ CSS
files in it. No idea how can I create a new page with the same header and
menus. I have updated that rental boat site home page BTW.
[image: image.png]

**Comment by schraderweb** [comment]
Hi Sanan,

Lets do a google meeting today to go over the TC boat rental site.

What time works best?

Bret Schrader
Account Manager at [Schrader.co](https://schrader.co)
1568 State St. #7
Grawn, MI 49637
Phone: (231) 620-3620

------- Original Message -------

**Comment by Sanan4li** [comment]
I missed the email. I will surely meet you tomorrow at 10:30pm my time.
which will be 1.30pm your time. I hope that would work for you. In the
meantime I am trying to make that page fully responsive.

**Comment by schraderweb** [comment]
That works to meet at 130pm my time Tues.

Thanks!

Bret Schrader
Account Manager at [Schrader.co](https://schrader.co)
1568 State St. #7
Grawn, MI 49637
Phone: (231) 620-3620

------- Original Message -------

**Comment by schraderweb** [comment]
Please put the attached logo on the Home page.
In the same spots as seen on the source page:
https://www.bluesky-tvc.com/

Thanks!

Bret Schrader
1568 State St. #7
Grawn, MI 49637
Phone: (231) 620-3620

------- Original Message -------

**Comment by Sanan4li** [comment]
meeting link?

**Comment by Sanan4li** [comment]
https://meet.google.com/yuh-rwkx-yfn

**Comment by schraderweb** [comment]
Did you add the new logo to that page?

Bret Schrader
Account Manager at [Schrader.co](https://schrader.co)
1568 State St. #7
Grawn, MI 49637
Phone: (231) 620-3620

------- Original Message -------

**Comment by Sanan4li** [comment]
I am online.. I hope we can meet today.

**Comment by schraderweb** [comment]
here ya go: meet.google.com/epy-gpwe-avx

Bret Schrader
Account Manager at [Schrader.co](https://schrader.co)
1568 State St. #7
Grawn, MI 49637
Phone: (231) 620-3620

------- Original Message -------

**Comment by schraderweb** [comment]
Some of the content is not centered......pls center it.

Pls put this map on the web site:
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d45337.07039236872!2d-85.64002681545585!3d44.748852049233264!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x881e32b2d7da29dd%3A0x47bfdc3f3f745621!2sTraverse%20City%2C%20MI!5e0!3m2!1sen!2sus!4v1652811430729!5m2!1sen!2sus" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

Bret Schrader
1568 State St. #7
Grawn, MI 49637
Phone: (231) 620-3620

------- Original Message -------

**Comment by schraderweb** [comment]
OK...thanks for the updates on this!

Bret Schrader
Account Manager at [Schrader.co](https://schrader.co)
1568 State St. #7
Grawn, MI 49637
Phone: (231) 620-3620

------- Original Message -------

**Comment by schraderweb** [comment]
Please clarify you can make this update detailed below asap:

Hi Sanan,
> >
> > Please create a new page on the site tjwaterfrontservices.com called:
> >
> > 6-tips-for-maintaining-your-seawalls.html
> >
> > Please use the attached article for the content.
> >
> > If it helps, here is an existing page with an article:
> > https://tjwaterfrontservices.com/tips-for-maintaining-boat-lift.html
> >
> > Thanks!

Bret Schrader
Account Manager at [Schrader.co](https://schrader.co)
1568 State St. #7
Grawn, MI 49637
Phone: (231) 620-3620

------- Original Message -------

**Comment by schraderweb** [comment]
What do you want to discuss?

Pls be more clear as to what you want.

Bret Schrader
Account Manager at [Schrader.co](https://schrader.co)
1568 State St. #7
Grawn, MI 49637
Phone: (231) 620-3620

------- Original Message -------

**Pull request merged**
